# Generated by Django 5.2.3 on 2025-06-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lname',
            new_name='last_name',
        ),
    ]
