# Generated by Django 5.2.3 on 2025-06-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='login',
            name='lname',
        ),
    ]
