# Generated by Django 5.2.3 on 2025-06-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_login_fname_remove_login_lname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
