# Generated by Django 5.2.3 on 2025-06-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fullname',
            new_name='name',
        ),
    ]
